CREATE TABLE [dbo].[TB_PRODUTORA] (
    [Id]             UNIQUEIDENTIFIER NOT NULL,
    [Nome]           NVARCHAR (MAX)   NULL,
    [ISOPais]        NVARCHAR (MAX)   NULL,
    [ProdutoraMaeId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_TB_PRODUTORA] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TB_PRODUTORA_TB_PRODUTORA_ProdutoraMaeId] FOREIGN KEY ([ProdutoraMaeId]) REFERENCES [dbo].[TB_PRODUTORA] ([Id])
);


GO
CREATE NONCLUSTERED INDEX [IX_TB_PRODUTORA_ProdutoraMaeId]
    ON [dbo].[TB_PRODUTORA]([ProdutoraMaeId] ASC);

