CREATE TABLE [dbo].[TB_USUARIOJOGO] (
    [Id]        UNIQUEIDENTIFIER NOT NULL,
    [UsuarioId] UNIQUEIDENTIFIER NOT NULL,
    [JogoId]    UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_TB_USUARIOJOGO] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TB_USUARIOJOGO_TB_JOGO_JogoId] FOREIGN KEY ([JogoId]) REFERENCES [dbo].[TB_JOGO] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_TB_USUARIOJOGO_TB_USUARIO_UsuarioId] FOREIGN KEY ([UsuarioId]) REFERENCES [dbo].[TB_USUARIO] ([Id]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_TB_USUARIOJOGO_JogoId]
    ON [dbo].[TB_USUARIOJOGO]([JogoId] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_TB_USUARIOJOGO_UsuarioId]
    ON [dbo].[TB_USUARIOJOGO]([UsuarioId] ASC);

